### ISSUE TITLE
Typo in astronaut readme.md

### ISSUE THREAD

**Issue by slater** [defold/tutorial-astronaut#2]
> The tilemap component, however, source its tilemap data from a separate file named "/main/level.tilemap".

should read:

> The tilemap component, however, sources its tilemap data from a separate file named "/main/level.tilemap".

**Comment by britzl** [comment]
Thank you!

https://github.com/defold/tutorial-astronaut/commit/84097c42b2b2d6d4be4eecd8653842632e3bb750
